codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 70%

comment:
  layout: "header, diff, flags, files"
  behavior: default
  require_changes: false